Training Epochs:   0%|                                                      | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mescalin/yitao/Documents/Code/3HP_Space/chytorch_test.py", line 262, in <module>
    main()
  File "/home/mescalin/yitao/Documents/Code/3HP_Space/chytorch_test.py", line 235, in main
    train_loss = train_model(model, train_loader, criterion, optimizer, device, epoch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mescalin/yitao/Documents/Code/3HP_Space/chytorch_test.py", line 132, in train_model
    wandb.log({"Train Loss per step",loss.item()})
  File "/scr/xindus/yitao/miniforge3/envs/aibio/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scr/xindus/yitao/miniforge3/envs/aibio/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 371, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scr/xindus/yitao/miniforge3/envs/aibio/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scr/xindus/yitao/miniforge3/envs/aibio/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1828, in log
    self._log(data=data, step=step, commit=commit)
  File "/scr/xindus/yitao/miniforge3/envs/aibio/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 1591, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary